/*
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * glassfish/bootstrap/legal/CDDLv1.0.txt or
 * https://glassfish.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * glassfish/bootstrap/legal/CDDLv1.0.txt.  If applicable,
 * add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your
 * own identifying information: Portions Copyright [yyyy]
 * [name of copyright owner]
 *
 * Copyright 2005 Sun Microsystems, Inc. All rights reserved.
 *//* Generated By:JavaCC: Do not edit this line. SPathParserConstants.java */
package org.apache.taglibs.standard.extra.spath;

public interface SPathParserConstants {

  int EOF = 0;
  int LITERAL = 1;
  int QNAME = 2;
  int NCNAME = 3;
  int NSWILDCARD = 4;
  int NCNAMECHAR = 5;
  int LETTER = 6;
  int DIGIT = 7;
  int COMBINING_CHAR = 8;
  int EXTENDER = 9;
  int UNDERSCORE = 10;
  int DOT = 11;
  int DASH = 12;
  int SLASH = 13;
  int STAR = 14;
  int COLON = 15;
  int START_BRACKET = 16;
  int END_BRACKET = 17;
  int AT = 18;
  int EQUALS = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<LITERAL>",
    "<QNAME>",
    "<NCNAME>",
    "<NSWILDCARD>",
    "<NCNAMECHAR>",
    "<LETTER>",
    "<DIGIT>",
    "<COMBINING_CHAR>",
    "<EXTENDER>",
    "\"_\"",
    "\".\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "\"=\"",
  };

}
